### ISSUE TITLE
Monster spawner

### ISSUE THREAD

**Issue by HipsterAF** [AppleDevelops/TesseractPM#10]
### Issue description
Can you add Monster spawner?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by NFGamerMC** [comment]
## This issue should’ve be closed, it serves no purpose.

**Please do not add feature requests in the issues**

**Comment by MasterOfTheRealm** [comment]
It is sort of an issue. Tesseract before 1.1 had monster spawners. So now it doesn't which means its a missing feature issue not a new feature request.
