### ISSUE TITLE
Spam Upon Joining

### ISSUE THREAD

**Issue by MasterOfTheRealm** [AppleDevelops/TesseractPM#13]
### Issue description

Upon Joining Console Starts To Spam.

### Steps to reproduce the issue

1. Join The Server.

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...
![screenshot_20170610-215332](https://user-images.githubusercontent.com/24680179/27004525-f96fe67e-4e27-11e7-82f7-56762c8b14dc.png)

**Comment by AppleDevelops** [comment]
You haven’t left any information, which cannot help us find the issue, this will be closed until you fill out the issue template.

**Comment by Qimie** [comment]
Lol still using Genisys app.
