### ISSUE TITLE
Mobs & enchants

### ISSUE THREAD

**Issue by Shadow166050** [AppleDevelops/TesseractPM#2]
Please add the rest of the mobs and enchants

**Comment by akaSnapy** [comment]
##This is a useless issue opened

**Comment by Shadow166050** [comment]
https://twitter.com/AppleDevelops/status/871961500910583808

I'm going off what he said so please go away your with your useless comment.

**Comment by akaSnapy** [comment]
If u want something on use the model issue gave u

**Comment by Shadow166050** [comment]
English??

**Comment by akaSnapy** [comment]
If my spelling is bad that doesnt mean you're more smart than me

**Comment by Shadow166050** [comment]
The post on Twitter said to say what you want added not follow the format, mobs and enchants are not added so obviously there's no format I need to follow such as version.

**Comment by Shadow166050** [comment]
Nor did I state anything about being smart. Do us all a favor and leave 😁

**Comment by AlanGone** [comment]
He's still allowed to comment what he wants added.

**Comment by NFGamerMC** [comment]
## This issue should’ve be closed, it serves no purpose.

**Please do not add feature requests in the issues**

**Comment by Shadow166050** [comment]
Please read above as he states I could.

**Comment by NFGamerMC** [comment]
Try not to be spammy about it, just add actual content.

**Comment by Shadow166050** [comment]
He said post what you want added in the issue section. Please go spam another thread.

**Comment by NFGamerMC** [comment]
This is not spam it is telling you to use your brain and code it yourself.

**Comment by Shadow166050** [comment]
Are you doing anything? No. So close your account as it serves no purpose.

**Comment by NFGamerMC** [comment]
Okay, I am done talking to you. Get a life and learn to code. 

**You seem to be the one causing this**

**Comment by Shadow166050** [comment]
Plus I've already talked to Apple and he plans on doing something else so
doing the code myself would be useless in the end.
