### ISSUE TITLE
Please do this

### ISSUE THREAD

**Issue by G2PCraft** [AppleDevelops/TesseractPM#3]
1. Make TesseractPM support API like Tesseract. 
2. Try to make code less different from Tesseract if you can.

**Comment by akaSnapy** [comment]
This is forked from PMMP so code its changed alot.

**Comment by junkdude** [comment]
^ meaning it will actually support most pmmp plugins also

**Comment by Dragonblitz10** [comment]
He means allow APIs from tesseract to be used?

**Comment by ImagicalGamer** [comment]
Useless issue.
