### ISSUE TITLE
Things u might add:)

### ISSUE THREAD

**Issue by akaSnapy** [AppleDevelops/TesseractPM#5]
### Issue description
Only 3 enchants are registred on Enchantment::init(). (you have to implement all of them)
Spawners aren't working also many monster eggs aren't implemented.
Windows 10 GUI is broke, i guess PMMP will fix.
Some old tesseract functions aren't implemented.

### Steps to reproduce the issue
No steps.

### OS and versions

* PocketMine-MP:Latest build of tesseract.
* PHP:7.0.19
* Server OS:Linux
* Game version: PE/Win10:Doesnt matter

**Comment by AppleDevelops** [comment]
There’s already a very broken Windows 10 support, I added a basic one last night.

**Comment by akaSnapy** [comment]
So it does support w10 gui?
