### ISSUE TITLE
WATER flows to y: 0 and warp back to the max building height 

### ISSUE THREAD

**Issue by XDqrkneZ** [AppleDevelops/TesseractPM#6]
### Issue description

 this was posted on pmmp repo but dktapps still don’t have a fix for it.
Look: https://github.com/pmmp/PocketMine-MP/issues/914 there are some pictures there
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by jasonwynn10** [comment]
Why are you wasting issue tickets? Don't be annoying 👎

**Comment by XDqrkneZ** [comment]
@jasonwynn10 I’m reporting this to apple because tesseract didn’t have this issue and i thought maybe he could fix it. You are the annoying one here fam

**Comment by AppleDevelops** [comment]
Since this is an open PR on PMMP, I’ll wait.

**Comment by jasonwynn10** [comment]
@AppleDevelops there's no point in doing the work yourself if it's already being worked on right? 😋

**Comment by AppleDevelops** [comment]
Exactly, I can focus on adding the features that I want and fix those, while the bugs Dylan is working on, will end up not wasting my time 👌
