### ISSUE TITLE
Missing Stuff

### ISSUE THREAD

**Issue by CortexPE** [AppleDevelops/TesseractPM#7]
ItemFrameDropEvent
![image](https://user-images.githubusercontent.com/17762324/26874744-59f87eca-4b44-11e7-88e7-e93f9c56b13f.png)

**Comment by CortexPE** [comment]
registerEnchantment()
![image](https://user-images.githubusercontent.com/17762324/26874790-89c86110-4b44-11e7-9732-2093cc71635c.png)

**Comment by HipsterAF** [comment]
add monster spawner too please
